

[workspace]
members = [
    "sys",
    "gdnative",
    "core",
    "graphics",
    "animation",
    "audio",
    "video",
    "visual_script",
    "editor",
    "input",
    "network",
    "arvr",
    "ui",
    "geom",
    "test",
    "bindings_generator",
    "examples/hello_world",
    "examples/spinning_cube",
    "examples/manually_registered",
]
