[workspace]
members = [
    "gdnative",
    "gdnative-bindings",
    "gdnative-core",
    "gdnative-derive",
    "gdnative-sys",
    "test",
    "bindings_generator",
    "examples/hello_world",
    "examples/spinning_cube",
    "examples/scene_create",
    "examples/signals",
    "examples/dodge_the_creeps",
    "examples/resource",
    "impl/proc_macros"
]

[profile.dev.package.miniserde]
opt-level = 0
