[package]
name = "gdnative_bindings_generator"
authors = ["The godot-rust developers"]
description = "Generates bindings for the Godot engine's gdnative classes from a json api description file."
documentation = "https://docs.rs/crate/gdnative_bindings_generator"
repository = "https://github.com/GodotNativeTools/godot-rust"
license = "MIT"
version = "0.8.1"
workspace = ".."
edition = "2018"

[dependencies]
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.15"
heck = "0.3.0"
