[package]
name = "gdnative"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative bindings."
documentation = "https://docs.rs/crate/gdnative"
repository = "https://github.com/GodotNativeTools/godot-rust"
version = "0.5.0"
license = "MIT"
workspace = ".."

[features]
gd_test = ["gdnative-core/gd_test"]

graphics = ["gdnative-graphics"]
physics = ["gdnative-physics"]
audio = ["gdnative-audio"]
video = ["gdnative-video"]
animation = ["gdnative-animation"]
network = ["gdnative-network"]
editor = ["gdnative-editor", "ui", "animation"]
visual_script = ["gdnative-visual_script"]
input = ["gdnative-input"]
ui = ["gdnative-ui", "video"]
arvr = ["gdnative-arvr"]

[dependencies]
gdnative-core = { path = "../core", version = "0.5.0" }
gdnative-common = { path = "../common", version = "0.5.0" }
gdnative-graphics = { optional = true, path = "../graphics", version = "0.5.0" }
gdnative-physics = { optional = true, path = "../physics", version = "0.5.0" }
gdnative-audio = { optional = true, path = "../audio", version = "0.5.0" }
gdnative-video = { optional = true, path = "../video", version = "0.5.0" }
gdnative-animation = { optional = true, path = "../animation", version = "0.5.0" }
gdnative-network = { optional = true, path = "../network", version = "0.5.0" }
gdnative-editor = { optional = true, path = "../editor", version = "0.5.0" }
gdnative-visual_script = { optional = true, path = "../visual_script", version = "0.5.0" }
gdnative-input = { optional = true, path = "../input", version = "0.5.0" }
gdnative-ui = { optional = true, path = "../ui", version = "0.5.0" }
gdnative-arvr = { optional = true, path = "../arvr", version = "0.5.0" }

[package.metadata.docs.rs]
all-features = true
