[package]
name = "gdnative"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative bindings."
documentation = "https://docs.rs/crate/gdnative"
repository = "https://github.com/godot-rust/godot-rust"
version = "0.8.1"
license = "MIT"
workspace = ".."
edition = "2018"

[features]
default = ["bindings"]

gd_test = ["gdnative-core/gd_test"]
bindings = ["gdnative-bindings"]

[dependencies]
gdnative-derive = { path = "../gdnative-derive", version = "0.8.1" }
gdnative-core = { path = "../gdnative-core", version = "0.8.1" }
gdnative-bindings = { optional = true, path = "../gdnative-bindings", version = "0.8.1" }

[package.metadata.docs.rs]
all-features = true
