[package]
name = "gdnative"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative bindings."
documentation = "https://docs.rs/crate/gdnative"
repository = "https://github.com/GodotNativeTools/godot-rust"
version = "0.4.0"
license = "MIT"
workspace = ".."

[features]
gd_test = []

[dependencies]
gdnative_core = { path = "../core", version = "0.4.0" }
gdnative_graphics = { path = "../graphics", version = "0.4.0" }
gdnative_physics = { path = "../physics", version = "0.4.0" }
gdnative_audio = { path = "../audio", version = "0.4.0" }
gdnative_video = { path = "../video", version = "0.4.0" }
gdnative_animation = { path = "../animation", version = "0.4.0" }
gdnative_network = { path = "../network", version = "0.4.0" }
gdnative_editor = { path = "../editor", version = "0.4.0" }
gdnative_visual_script = { path = "../visual_script", version = "0.4.0" }
gdnative_input = { path = "../input", version = "0.4.0" }
gdnative_ui = { path = "../ui", version = "0.4.0" }
gdnative_arvr = { path = "../arvr", version = "0.4.0" }
libc = "0.2"
bitflags = "1.0"

[build-dependencies]
gdnative_bindings_generator = { path = "../bindings_generator" }
