[package]
name = "gdnative"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative bindings."
documentation = "https://docs.rs/crate/gdnative"
repository = "https://github.com/godot-rust/godot-rust"
version = "0.9.0-preview.0"
license = "MIT"
workspace = ".."
readme = "../README.md"
edition = "2018"

[features]
default = ["bindings"]
formatted = ["gdnative-bindings/formatted", "gdnative-bindings/one_class_one_file"]

gd_test = ["gdnative-core/gd_test"]
bindings = ["gdnative-bindings"]

no_profiling = []

[dependencies]
gdnative-derive = { path = "../gdnative-derive", version = "=0.9.0-preview.0" }
gdnative-core = { path = "../gdnative-core", version = "=0.9.0-preview.0" }
gdnative-bindings = { optional = true, path = "../gdnative-bindings", version = "=0.9.0-preview.0" }

[package.metadata.docs.rs]
all-features = true
