[package]
name = "gdnative-bindings"
authors = ["The godot-rust developers"]
description = "The Godot game engine's automatcally generated bindings to Godot classes."
documentation = "https://docs.rs/crate/gdnative-bindings"
repository = "https://github.com/GodotNativeTools/godot-rust"
version = "0.7.0"
license = "MIT"
workspace = ".."
edition = "2018"

[dependencies]
gdnative-sys = { path = "../gdnative-sys", version = "0.7.0" }
gdnative-core = { path = "../gdnative-core", version = "0.7.0" }
libc = "0.2"
bitflags = "1.2"

[build-dependencies]
gdnative_bindings_generator = { path = "../bindings_generator", version = "0.7.0" }
