[package]
name = "gdnative-core"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative core bindings."
documentation = "https://docs.rs/crate/gdnative"
repository = "https://github.com/GodotNativeTools/godot-rust"
version = "0.5.0"
license = "MIT"
workspace = ".."
edition = "2018"

[features]
gd_test = []

[dependencies]
gdnative-sys = { path = "../gdnative-sys", version = "0.5.0" }
libc = "0.2"
bitflags = "1.0"
euclid = "0.19.6"

[build-dependencies]
gdnative_bindings_generator = { path = "../bindings_generator", version = "0.2.0" }
