[package]
name = "gdnative-core"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative core bindings."
documentation = "https://docs.rs/crate/gdnative-core"
repository = "https://github.com/godot-rust/godot-rust"
homepage = "https://godot-rust.github.io/"
version = "0.9.3"
license = "MIT"
workspace = ".."
edition = "2018"

[features]
default = ["nativescript"]
gd_test = []
nativescript = ["bitflags", "parking_lot"]
type_tag_fallback = []

[dependencies]
gdnative-sys = { path = "../gdnative-sys", version = "0.9.3" }
libc = "0.2"
approx = "0.4.0"
glam = "0.14.0"
indexmap = "1.6.0"
ahash = "0.7.0"

gdnative-impl-proc-macros = { path = "../impl/proc_macros", version = "=0.9.3" }

bitflags = { version = "1.2", optional = true }
parking_lot = { version = "0.11.0", optional = true }
atomic-take = "1.0.0"
