[package]
name = "gdnative-core"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative core bindings."
documentation = "https://docs.rs/crate/gdnative-core"
repository = "https://github.com/godot-rust/godot-rust"
version = "0.8.1"
license = "MIT"
workspace = ".."
edition = "2018"

[features]
default = ["nativescript"]
gd_test = ["approx"]
nativescript = ["bitflags", "parking_lot"]

[dependencies]
gdnative-sys = { path = "../gdnative-sys", version = "0.8.1" }
libc = "0.2"

euclid = "0.20.1"

gdnative-impl-proc-macros = { path = "../impl/proc_macros", version = "=0.9.0" }

# Used for float comparisons in godot tests
approx = { version = "0.3.2", optional = true }

bitflags = { version = "1.2", optional = true }
parking_lot = { version = "0.9.0", optional = true }

[build-dependencies]
gdnative_bindings_generator = { path = "../bindings_generator", version = "0.8.1" }
quote = "1.0.2"
