[package]
name = "gdnative-core"
authors = ["The godot-rust developers"]
description = "The Godot game engine's gdnative core bindings."
documentation = "https://docs.rs/crate/gdnative-core"
repository = "https://github.com/GodotNativeTools/godot-rust"
version = "0.8.1"
license = "MIT"
workspace = ".."
edition = "2018"

[features]
gd_test = ["approx"]

[dependencies]
gdnative-sys = { path = "../gdnative-sys", version = "0.8.1" }
libc = "0.2"
bitflags = "1.2"
euclid = "0.20.1"
parking_lot = "0.9.0"

# Used for float comparisons in godot tests
approx = { version = "0.3.2", optional = true }

[build-dependencies]
gdnative_bindings_generator = { path = "../bindings_generator", version = "0.8.1" }
